version: "2"
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - api-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
